### ISSUE TITLE
Need to change option string

### ISSUE THREAD

**Issue by hiddenillusion** [tomspencer/volatility#1]
Looks like the short options to **_C**_ is conflicting with the main **_C/confsize**_ options

traceback:

```
Volatility Foundation Volatility Framework 2.5
Traceback (most recent call last):
  File "/opt/tools/volatility/vol.py", line 192, in <module>
    main()
  File "/opt/tools/volatility/vol.py", line 174, in main
    command = cmds[module](config)
  File "/other_plugins/community/TomSpencer/usnparser.py", line 546, in __init__
    action = 'store_true')
  File "/opt/tools/volatility/volatility/conf.py", line 363, in add_option
    self.optparser.add_option("-{0}".format(short_option), "--{0}".format(option), **args)
  File "/usr/lib/python2.7/optparse.py", line 1021, in add_option
    self._check_conflict(option)
  File "/usr/lib/python2.7/optparse.py", line 996, in _check_conflict
    option)
optparse.OptionConflictError: option -C/--check: conflicting option string(s): -C
```

**Comment by tomspencer** [comment]
Hi @hiddenillusion, thanks for the heads-up on this.

I looked in to it, and the issue seems to be a conflict with another community plugin. Volatility itself has no "C" short option, and usnparser works fine with volatility 2.5 by itself.

Based on the "community" path in your trace, and the "confsize" option you mentioned, i'm assuming you're loading the volatility community repo. If that is the case, the conflict is almost certainly with the dyrescan plugin from KudelskiSecurity. Dyrescan loads first (because of alphabetical ordering), so it gets to register the "C" short option, then when volatility gets to usnparser the "C" option is already taken so it errors out. I could potentially change/remove that option from usnparser, but i'd rather not start a trend of having to change the options over and over just because my name is alphabetically challenged.

This is really a symptom of a larger issue, which is that volatility registers every plugin's options whether that plugin is actually being run or not. I believe there are good reasons they did this, but as shown here it just doesn't scale if you start pulling in lots of third party plugins. It would probably be useful to raise an issue with the volatility team in this area to change how this works.

In the mean time, just to get things running locally with the community plugins, i would suggest manually removing the "C" short option either from dyrescan or usnparser - whichever one you use less. :)
